version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: fatec
      MYSQL_DATABASE: fateczlspringaula
      MYSQL_USER: fatec
      MYSQL_PASSWORD: fatec
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
